#!/usr/bin/env bash

set -ex

usermod -d /opt/solr solr

mkdir -p /opt/solr/server/solr/${PROJECT_NAME}
mkdir -p /opt/solr/server/solr/${PROJECT_NAME}/data
chmod -R 777 /opt/solr/server/solr/${PROJECT_NAME}

echo "export PATH=/usr/local/openjdk-11:$PATH" >> /opt/solr/.bashrc
echo "export PATH=/usr/local/openjdk-11:$PATH" >> /root/.bashrc

cp -R /opt/solr/server/solr/configsets/_default/conf /opt/solr/server/solr/${PROJECT_NAME}

cd /opt/solr

export PATH=/usr/local/openjdk-11:$PATH

/opt/solr/bin/solr create_core -c $SOLR_CORE

