#!/usr/bin/env bash

set -ex

SOLR_CORE_HOME=/var/solr/data
CONFIG_SET=drupal
CONFIG_HOST=localhost
CONFIG_CORE=${PROJECT_NAME}
CONFIG_INSTANCE_DIR=${SOLR_CORE_HOME}/${CONFIG_CORE}

mkdir -p ${SOLR_CORE_HOME}/${PROJECT_NAME}
mkdir -p ${SOLR_CORE_HOME}/${PROJECT_NAME}/data
mkdir -p ${SOLR_CORE_HOME}/${PROJECT_NAME}/conf
chmod -R 777 ${SOLR_CORE_HOME}/${PROJECT_NAME}

cd /opt/solr

export PATH=/usr/local/openjdk-11:$PATH
curl -sIN "http://${CONFIG_HOST}:8983/solr/admin/cores?action=CREATE&name=${CONFIG_CORE}&configSet=${CONFIG_SET}" \
		| head -n 1 | awk '{print $$2}' | grep -q 200

